version: "3.8"

services:
  person-name-annotator:
    image: nlpsandbox/person-name-annotator-example:latest
    build:
      context: server
      dockerfile: Dockerfile
    container_name: person-name-annotator
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/healthCheck
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8080:8080"