version: "3.8"

services:
  person-name-annotator:
    image: nlpsandbox/person-name-annotator-example:latest
    build:
      context: server
      dockerfile: Dockerfile
    container_name: nlp-person-name-annotator
    ports:
      - "8080:8080"